config/routes.rb
Ecs::Application.routes.draw do
  resources  :payment_notifications, only: [:create]
  devise_for :admins
  resources  :admins
  resources  :attendees
  resources  :vendors
  resources  :lectures

  root 'static_pages#index'
  match '/payment_notifications', to: 'payment_notifications#create', via: 'post'
  match '/faq',                   to: 'static_pages#faq',             via: 'get'
  # match '/lectures',              to: 'lectures#new',                 via: 'get'
  match '/current_vendors',       to: 'static_pages#vendors',         via: 'get'
  match '/vendor_success',        to: 'static_pages#vendor_success',  via: 'get'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  before_save { self.email = email.downcase }
  has_one   :payment_notification
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: /@/ }, uniqueness: { case_sensitive: false }
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
	validates :topic, presence: true
	validates :email, presence: true
end

app/models/lectures.rb
class Lectures < ActiveRecord::Base
	validates :topic, presence: true
	validates :email, presence: true
end

app/models/payment_notification.rb
class PaymentNotification < ActiveRecord::Base
	belongs_to :attendee
	serialize :params
	after_create :mark_attendee_paid

	private

	def mark_attendee_paid
		if status == 'Completed'
			attendee.update_attribute(:paid, Time.now)
			UserMailer.welcome_email(attendee).deliver
		end
	end
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: /@/ }, uniqueness: { case_sensitive: false }
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  	@admins = Admin.all
  end

  def show
  	@admin = Admin.find(params[:id])
  end

  def new
  	@admin = Admin.new
  end

  def create
  	@admin = Admin.create(admin_params)
  	if @admin.save
  		redirect_to admins_path
  	else
  		render 'new'
  	end
  end

  private
  	def admin_params
  		params.require(:admin).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path
  end

  def current_ability
    @current_ability ||= Ability.new(current_admin)
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def index
    @attendees = Attendee.all
    authorize! :manage, @attendees
  end

  def show
    @attendee = Attendee.find(params[:id])
  end  

	def new
    @attendee = Attendee.new
  end

  def create
    @attendee = Attendee.new(attendee_params)
    if @attendee.save 
      redirect_to @attendee
    else
      render 'new'
    end
  end

private
  def attendee_params
    params.require(:attendee).permit(:first_name, :last_name, :email, :phone, :address, :city, :state, :zip, :industry, :questions)
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def index
  	@lectures = Lecture.all
  	authorize! :manage, @lectures
	end

	def new
		@lecture = Lecture.new
	end

	def create
		@lecture = Lecture.new(lecture_params)
		if @lecture.save
			flash[:success] = 'Thanks for the input.'
			redirect_to new_lecture_path
		else
			render 'new'
		end
	end

  private

	def lecture_params
		params.require(:lecture).permit(:topic, :email)
	end
end

app/controllers/payment_notifications_controller.rb
class PaymentNotificationsController < ApplicationController
  protect_from_forgery :except => [:create]

  def create
  	PaymentNotification.create!(:params => params, :attendee_id => params[:invoice], :status => params[:payment_status], :transaction_id => params[:txn_id])
  	render nothing: true
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def vendors
  end

  def faq
  end

  def vendor_success
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def index
  	@vendors = Vendor.all
    authorize! :read, @vendors
  end

  def show
    @vendor = Vendor.find(params[:id])
  end  

	def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      UserMailer.welcome_email(@vendor).deliver
      redirect_to vendor_success_path
    else
      render 'new'
    end
  end

private
  def vendor_params
    params.require(:vendor).permit(:first_name, :last_name, :email, :phone, :address, :city, :state, :zip, :vendor_name, :comments, :speak_topic, :speak_topic_ceu)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = 'ECS'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/payment_notifications_helper.rb
module PaymentNotificationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/admins/_edit.html.erb
<h1>Edit <%= "#{@admin.first_name} #{@admin.last_name}" %></h1>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <h3>Profile Information</h3>
	<%= f.label          :first_name %>
	<%= f.text_field     :first_name, autofocus: true %>
  <%= f.label          :last_name %>
	<%= f.text_field     :last_name %>
	<%= f.label          :role %>
	<%= f.text_field     :role %>

	<h3>Login Information</h3>
	<%= f.label          :email %>
  <%= f.email_field    :email %>
  <%= f.label          :password %>
  <%= f.password_field :password %>
  <%= f.label          :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <h3>Confirm Changes</h3>
  <%= f.label          :current_password %>
  <%= f.password_field :current_password %>

  <span class='button' style='display: block;'><%= f.submit 'Update' %></span>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to 'Cancel my account', registration_path(resource_name), :confirm => 'Are you sure?', :method => :delete %>.</p>

<%= link_to 'Back', :back %>

app/views/admins/index.html.erb
<% if current_admin %>
	<h1>Admins</h1>

	<% if @admins.any? %>
		<% @admins.each do |admin| %>
			<strong><%= "#{admin.first_name} #{admin.last_name}" %></strong>
			<small><%= "#{admin.email}" %></small>
		<% end %>
	<% else %>
		<h2>No admins.</h2>
	<% end %>
<% else %>
	<div class='center container'>
		<br><br>
  	<h3>Oops. You don't have permission to view this page</h3>
  	<%= link_to 'Back', root_path %>
  </div>
<% end %>

app/views/admins/new.html.erb
<% if current_admin %>
  <h1>Create Admin</h1>

  <%= form_for @admin do |f| %>
    <%= f.label          :first_name %>
    <%= f.text_field     :first_name, autofocus: true %>
    <%= f.label          :last_name %>
    <%= f.text_field     :last_name %>
    <%= f.label          :email %>
    <%= f.email_field    :email, placeholder: 'example@user.com' %>
    <%= f.label          :password %>
    <%= f.password_field :password %>
    <%= f.label          :password_confirmation %>
    <%= f.password_field :password_confirmation %><br>
    <%= f.submit 'Create' %>
  <% end %>
<% else %>
  <h3>Oops. You don't have permission to view this page</h3>
  <%= link_to 'Back', root_path %>
<% end %>

app/views/admins/show.html.erb
<% if current_admin %>
	<h1><%= "#{@admin.first_name} #{@admin.last_name}" %></h1>

	<span>
		<%= "#{@admin.email}" %>
		<%= "#{@admin.role}" %>
	</span>
<% else %>
  <h3>Oops. You don't have permission to view this page</h3>
  <%= link_to 'Back', root_path %>
<% end %>

app/views/attendees/_attendee_error_messages.html.erb
<% if @attendee.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-error'>
      The form contains <%= pluralize(@attendee.errors.count, 'error') %>.
    </div>
    <ul>
    <% @attendee.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/attendees/index.html.erb
<% provide(:title, 'All Attendees') %>
<div class='container'>
  <h1>Attendees</h1>

  <% if @attendees.any? %>
  	<table class='table table-striped'>
      <tr>
        <th class='orange'>First Name</th>
        <th class='orange'>Last Name</th>
        <th class='orange'>Email</th>
        <th class='orange'>Phone</th>
        <th class='orange'>Industry</th>
        <th class='orange'>Questions</th>
        <th class='orange'>Paid</th>
      </tr>
      <% @attendees.each do |attendee| %>
    		<tr>
          <td><%= "#{attendee.first_name}" %></td>
          <td><%= "#{attendee.last_name}"  %></td>
    	 	  <td><%= "#{attendee.email}"      %></td>
    	   	<td><%= "#{attendee.phone}"      %></td>
          <td><%= "#{attendee.industry}"   %></td>
          <td><%= "#{attendee.questions}"  %></td>
          <% if attendee.paid %>
            <td><%= attendee.paid.strftime("%m-%d-%Y") %></td>
    	    <% else %>
            <td></td>
          <% end %>
        </tr>
      <% end %>
    </table>
  <% else %>
    <h2>No attendees.</h2>
  <% end %>
</div>

app/views/attendees/new.html.erb
<% provide(:title, 'Attendees') %>
<div class='small-banner'>
	<span class='above-brand'>Thank You for Your Interest in The First Annual<span>
	<span class='brand'>Engineered Corrosion Solutions 2014 Conference</span>
</div>

<div class='container'>
	<div class='tall card'>
		<span class='card-header'>Attendee Sign Up</span>
		<div class='form span4'>
			<%= form_for @attendee do |f| %>
				<%= render 'attendees/attendee_error_messages' %>
				<span class='notice'>You will be prompted to pay $35 joining fee on next screen.</span>
				<div class='controls controls-row'>
					<%= f.text_field  :first_name, placeholder: 'First Name', autofocus: true, class: 'span2 dropshadow' %>
					<%= f.text_field  :last_name,  placeholder: 'Last Name', class: 'span2 dropshadow' %>
				</div>
				<div class='controls controls-row'>
				  <%= f.email_field :email, placeholder: 'Email', class: 'span2 dropshadow' %>
					<%= f.text_field  :phone, placeholder: 'Phone Number', class: 'span2 dropshadow' %>
				</div>
				<div class='controls controls-row'>
					<%= f.text_field  :address, placeholder: 'Street Address', class: 'span4 dropshadow' %>
				</div>
				<div class='controls controls-row'>
					<%= f.text_field  :city, placeholder: 'City', class: 'span2 dropshadow' %>
					<%= f.text_field  :state, placeholder: 'State', class: 'span1 dropshadow' %>
					<%= f.text_field  :zip, placeholder: 'Zip', class: 'span1 dropshadow' %>
				</div>
				<div class='controls controls-row'>
					<%= f.text_field  :industry, placeholder: 'Company', class: 'span4 dropshadow' %>
				</div>
				<div class='controls controls-row'>
					<%= f.text_area   :questions, placeholder: 'Questions, Concerns and Comments', class: 'span4 dropshadow', rows: '3' %>
				</div>
			  <span class='pull-right'>
			  	<%= f.submit 'Register', class: 'btn btn-primary' %>
			 	</span>
			<% end %>
		</div>
	</div>

	<div class='wide card'>
		<span class='quick-info'>
			<span class='more-info bold'>Letter from the host..</span>
	</div>
</div>
</div>
</div>

</div>

app/views/attendees/show.html.erb
<% provide(:title, "Registration") %>
<div class='small-banner'>
	<span class='above-brand'>Thank you for Participating in <span>
	<span class='brand'>Engineered Corrosion Solutions 2014</span>
</div>

<div class='container'>
	<div class='tall card'>
		<% if @attendee.paid? %>
			<span class='card-header'>Pay Registration</span>
			<div class='payment span4'><h3>PAID</h3></div>
		<% else %>
			<span class='card-header'>Pay Registration</span>
			<div class='payment span4'>
			  <!-- CHANGE THE URL HERE -->
				<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_blank">
				<input type="hidden" name="cmd" value="_s-xclick">
				<!-- CHANGE THE HOSTED_BUTTON_ID HERE -->
				<input type="hidden" name="hosted_button_id" value="NY7FV77SGNH98">
				<%= hidden_field_tag 'invoice', @attendee.id %>
				<!-- CHANGE THE CALLBACK URL HERE -->
				<%= hidden_field_tag 'notify_url', 'http://rails-ecs.herokuapp.com/payment_notifications' %>
				<input type="hidden" name="bn" value="PP-BuyNowBF:btn_paynowCC_LG.gif:NonHosted">
				<!-- REMOVE 'SANDBOX' FROM URL HERE -->
				<input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
				<!-- REMOVE 'SANDBOX' FROM URL HERE -->
				<img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
			</form>
			</div>
		<% end %>
		</span>
	</div>

	<div class='wide card'>
		<span class='quick-info'>
			<% if @attendee.paid? %>
				<span class='more-info bold'>Payment successful:</span>
				<span class='more-info'><i class='icon-chevron-right'></i>
					Registration complete, see you at the show.</span>
			<% else %>
				<span class='more-info bold'>Payment required:</span>
				<span class='more-info' style='color: red;'><i class='icon-chevron-right'></i>
					Registration incomplete, please pay fee via PayPal.</span>
			<% end %>
		</span>
	</div>

	<div class='wide card'>
		<span class='quick-info'>
			<span class='more-info bold'>Email:</span>
			<span class='more-info'><i class='icon-chevron-right'></i>
				You will receive an email shortly confirming your registration.</span>
			<span class='more-info'><i class='icon-chevron-right'></i>
				After payment is complete you'll receive an email with your receipt.</span> 
		</span>
	</div>

</div>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <small>
    Contact ECS by <a href='mailto:info@engineeredcorrosionsolutions.org?subject=ECS%20Trade%20Show%20Contact'>email</a> or call
847.423.2167
  </small>
  <nav>
    <ul>
      <li><small>Website by <%= link_to 'HunterMeyer', 'http://huntermeyer.com', target: '_blank' %></small></li>
    </ul>
  </nav>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45674216-2', 'engineeredcorrosionsolutions.com');
  ga('send', 'pageview');

  </script>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top navbar-inverse'>
  <div class='navbar-inner'>
    <div class='container'>
      <div class='logo-top'>
        <%= link_to 'ECS | 2014', root_path, id: 'logo' %>
        <span class='sponsor'>
          <span class='assoc'>In asssociation with</span>
          <a href='http://www.chicagocoatingsgroup.com/' alt='CCG' target='_blank'>
            <span class='link'>Chicago Coatings Group</span>
          </a>
        </span>
      </div>
      <nav>
        <ul class='nav pull-right'>
          <li><%= link_to 'Home',           root_path %></li>
          <li><%= link_to 'Lectures',       new_lecture_path %></li>
          <li><%= link_to 'Exhibitor Listing', current_vendors_path %></li>
          <% if current_admin %>
            <li class='dropdown'>
              <a href='#' class='dropdown-toggle' data-toggle='dropdown'><%= current_admin.first_name %><b class='caret'></b></a>
              <ul class='dropdown-menu'>
                <li><%= link_to 'Attendees',    attendees_path %></li>
                <li><%= link_to 'Exhibitors',   vendors_path %></li>
                <li><%= link_to 'Lectues',      lectures_path %></li>
                <li class='divider'></li>
                <li><%= link_to 'Logout',       destroy_admin_session_path, method: :delete %> </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Exhibitors',   new_vendor_path %></li>
            <li><%= link_to 'Attendees', new_attendee_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sponsor.html.erb
<div class='sponsor-banner'>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
  
  <%= yield %>  

  <div class='center container'>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/lectures/_lectures_error_messages.html.erb
<% if @lecture.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-error'>
      The form contains <%= pluralize(@lecture.errors.count, 'error') %>.
    </div>
    <ul>
    <% @lecture.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/lectures/index.html.erb
<% provide(:title, 'Lecture Suggestions') %>
<div class='container'>
  <h1>Lecture Suggestions</h1>

  <% if @lectures.any? %>
  	<table class='table table-striped'>
      <tr>
        <th class='orange'>Email</th>
        <th class='orange'>Topic</th>
        <th class='orange'>Suggested</th>
      </tr>
      <% @lectures.each do |lecture| %>
    		<tr>
          <td><%= "#{lecture.email}" %></td>
          <td><%= "#{lecture.topic}"  %></td>
          <td><%= lecture.created_at.strftime("%m-%d-%Y") %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <h2>No lecture suggestions.</h2>
  <% end %>
</div>

app/views/lectures/new.html.erb
<% provide(:title, 'Lectures') %>
<div class='small-banner'>
  <span class='above-brand'>Current Lectures<span>
  <span class='brand'>Engineered Corrosion Solutions 2014</span>
</div>

<div class='center container'>
  <% flash.each do |key, value| %>
    <div class='alert alert-<%= key %>'><%= value %></div>
  <% end %>
</div>

<div class='container'>
  <div class='tall card'>
    <span class='card-header'>Suggest a Lecture</span>
    <div class='form span4'>
      <%= form_for @lecture do |f| %>
        <%= render 'lectures_error_messages' %>
        <div class='controls controls-row'>
          <%= f.email_field  :email, placeholder: 'your@email.com', autofocus: true, class: 'span4 dropshadow' %>
        </div>
        <div class='controls controls-row'>
          <%= f.text_field  :topic,  placeholder: 'Suggest a new topic...', class: 'span4 dropshadow' %>
        </div>
        <span class='pull-right'>
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </span>
      <% end %>
    </div>
  </div>
  
  <div class='wide card'>
    <span class='quick-info'>
      <span class='more-info bold'>Lectures:</span>
      <span class='more-info'><i class='icon-chevron-right'></i>
        Fundamentals of Impressed Current and Sacrificial Cathodic Protection Systems.</span>
        <span class='speaker'><span class='soft'>Speaker:</span> Mr. Jim Dooley</span>
        <span class='speaker'><span class='soft'>Representing:</span> Corrpro</span>
      <span class='more-info'><i class='icon-chevron-right'></i>
        Understanding the Attributes of Hot-Dip Galvanizing.</span>
        <span class='speaker'><span class='soft'>Speaker:</span> Mr. Kevin Irving</span>
        <span class='speaker'><span class='soft'>Representing:</span> AZZ Galvanizing</span>
      <span class='more-info'><i class='icon-chevron-right'></i>
        Fundamentals of Surface Preparation and the Benefits of Media Blasting.</span>
        <span class='speaker'><span class='soft'>Speaker:</span> Mr. Joe Sergio</span>
        <span class='speaker'><span class='soft'>Representing:</span> Polar Clean</span>
      <span class='more-info'><i class='icon-chevron-right'></i>
        Technologies and Application of Cured-in-Place Piping Solutions (CIPP).</span>
        <span class='speaker'><span class='soft'>Speaker:</span> Mr. Kevin Coburn</span>
        <span class='speaker'><span class='soft'>Representing:</span> Insituform Technologies</span>
      <span class='more-info'><i class='icon-chevron-right'></i>
        Remediation of corrosion by use of fibre reinforced polymers (FRP).</span>
        <span class='speaker'><span class='soft'>Speaker:</span> Mr. Pete Kratzer</span>
        <span class='speaker'><span class='soft'>Representing:</span> Fibrwrap</span>
      <span class='more-info'><i class='icon-chevron-right'></i>
        Understanding the Science of Corrosion on a Fundamental Level.</span>
        <span class='speaker'><span class='soft'>Speaker:</span> TBD</span>
        <span class='speaker'><span class='soft'>Representing:</span> TBD</span>
      <span class='more-info'><i class='icon-chevron-right'></i>
        Basics of Barrier Coatings, Permeation and the Cold Wall Effect.</span>
        <span class='speaker'><span class='soft'>Speaker:</span> TBD</span>
        <span class='speaker'><span class='soft'>Representing:</span> TBD</span>
        <span class='more-info bold'>Additional Lectures are Being Developed</span>
      </span>
    </span>
  </div>
</div>
</div>

app/views/payment_notifications/create.html.erb
<h1>PaymentNotifications#create</h1>
<p>Find me in app/views/payment_notifications/create.html.erb</p>

app/views/static_pages/faq.html.erb
<% provide(:title, 'FAQ') %>
<div class='container'>
  <h1>FAQ</h1>
  <h2>This is the FAQ page.</h2>
</div>

app/views/static_pages/index.html.erb
<div class='banner'>
</div>

<div class='center container'>

	<div class='tall-outer'>
		<div class='tall-inner card'>
			<span class='card-header'>Sign Up</span>
			<span class='main-info'>
				<div class='signup-button' id='vendor'>
					<%= link_to '<i class="icon-user icon-white"></i> Exhibitor'.html_safe, new_vendor_path, class: 'button-link' %>
				</div>
				<div class='signup-button' id='attendee'>
					<%= link_to '<i class="icon-user icon-white"></i> Attendee'.html_safe, new_attendee_path, class: 'button-link' %>
				</div>
			</span>
		</div>
		<div class='tall-inner card'>
		<span class='card-header'>Event Info</span>
			<span class='main-info'>
				<span class='big-info'>Thursday, March 13, 2014</span>
				<span class='small-info'>9am - 5pm</span>
				<span class='big-info'>Doubletree Hilton Hotel</span>
				<span class='small-info'>9599 Skokie Blvd.<br>Skokie, IL 60776</span>
				<span class='xsmall-info'><a href='http://doubletree3.hilton.com/en/hotels/illinois/doubletree-by-hilton-hotel-chicago-north-shore-conference-center-CHICCDT/index.html' target='_blank'><i class='icon-share'></i> Website</a>
				</span>
				<div class='googlemap'>
					<%= link_to 'http://goo.gl/maps/7pwbd', target: '_blank' do %>
						<img class='map' src='https://googledrive.com/host/0BzGPB-VGfaP5bS0tU0FBeFE5UWc/map2.png'>
					<% end %>
				</div>
			</span>
		</div>
	</div>	

	<div class='wide card'>
		<span class='card-header'>Engineered Corrosion Solutions 2014</span>
		<span class='quick-info show'>
			<span class='show-about'>A unique conference focusing on the fundamentals of corrosion from an economic and technical perspective.
				</span>
		</span>
	</div>

	<div class='wide card'>
		<span class='quick-info'>
			<i class='icon-chevron-right'></i>
			<span class='bold'>Corrosion is fundamental to virtually every industry, facility and building.</span>
			<span class='more-info'>Whether we are talking about corrosion under insulation at a refinery, a leaking cooling tower basin at a commercial building, peeling paint on a condominium association in Chicago, or corrosion on a circuit board, the fundamental corrosion mechanisms are identical.
			</span>
		</span>
	</div>

	<div class='wide card'>
		<span class='quick-info'>
			<i class='icon-chevron-right'></i>
			<span class='bold'>ECS is Unique, and Relevant to all Industrial and Commercial Facilities.</span>
      <span class='more-info'>We focus exclusively on understanding corrosion and erosion on a practical, technical and fundamental level. ECS presents state-of-the-art remedial solutions, and lectures on the total economic and managerial decision-making process.
			</span>
		</span>
	</div>

	<div class='wide card'>
		<span class='quick-info'>
			<i class='icon-chevron-right'></i>
			<span class='bold'>ECS Will Include Pull-Out Sessions For Clients.</span>
      <span class='more-info'>Developed specifically to understand specific corrosion and erosion issues, the process associated with these issues, the vast variety of solutions available and, most importantly, understanding the economics of choosing the appropriate remedial solution.
      </span>
		</span>
	</div>

	<div class='wide card'>
		<span class='quick-info'>
			<i class='icon-chevron-right'></i>
			<span class='bold'>ECS Evaluates Each Vendor to Ensure High Standards.</span>
			<span class='more-info'>Each vendor is vetted to ensure that they maintain an extremely high level of integrity, provide outstanding customer service, are highly knowledgeable, and exhibit uniquely valuable products and services.
			</span>
		</span>
	</div>
</div>